apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: common
  namespace: dev
spec:
  refreshInterval: 10s
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-store         
  target:
    name: common
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: common
